/*
 * This file is generated by jOOQ.
 */
package com.jerome.jooq;


import com.jerome.jooq.tables.Events;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.EVENTS</code>.
     */
    public static final Events EVENTS = com.jerome.jooq.tables.Events.EVENTS;
}
