/*
 * This file is generated by jOOQ.
 */
package com.jerome.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventAlert implements Serializable {

    private static final long serialVersionUID = -1451782979;

    private final UUID    id;
    private final String  eventId;
    private final Integer duration;
    private final String  type;
    private final String  host;
    private final Boolean alert;

    public EventAlert(EventAlert value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.duration = value.duration;
        this.type = value.type;
        this.host = value.host;
        this.alert = value.alert;
    }

    public EventAlert(
        UUID    id,
        String  eventId,
        Integer duration,
        String  type,
        String  host,
        Boolean alert
    ) {
        this.id = id;
        this.eventId = eventId;
        this.duration = duration;
        this.type = type;
        this.host = host;
        this.alert = alert;
    }

    public UUID getId() {
        return this.id;
    }

    public String getEventId() {
        return this.eventId;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public String getType() {
        return this.type;
    }

    public String getHost() {
        return this.host;
    }

    public Boolean getAlert() {
        return this.alert;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventAlert (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(duration);
        sb.append(", ").append(type);
        sb.append(", ").append(host);
        sb.append(", ").append(alert);

        sb.append(")");
        return sb.toString();
    }
}
